[package]
name = "r-glaredb"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
# savvy = "0.6.3" # TODO: update after > 0.6.3 released
savvy = { git = "https://github.com/yutannihilation/savvy", rev = "08895ae2d8207ea2918fc5bb31f826c2e88a2959" }
datafusion = { version = "36.0.0", features = ["avro"] }
tokio = { version = "1", features = ["full"] }
arrow = { version = "50.0.0", features = ["ffi"] }
pollster = "0.3.0"
thiserror = "1.0"
url = "2.5.0"
anyhow = "1.0.83"
async-trait = "0.1.80"
futures = "0.3.30"
uuid = "1.8.0"
once_cell = "1.19.0"
glaredb = { git = "https://github.com/GlareDB/glaredb", rev = "f71c2f0ad220ac54c84724330224f43c860bffb9" }
ioutil = { git = "https://github.com/GlareDB/glaredb", rev = "f71c2f0ad220ac54c84724330224f43c860bffb9" }
sqlexec = { git = "https://github.com/GlareDB/glaredb", rev = "f71c2f0ad220ac54c84724330224f43c860bffb9" }
metastore = { git = "https://github.com/GlareDB/glaredb", rev = "f71c2f0ad220ac54c84724330224f43c860bffb9" }
telemetry = { git = "https://github.com/GlareDB/glaredb", rev = "f71c2f0ad220ac54c84724330224f43c860bffb9" }
pgsrv = { git = "https://github.com/GlareDB/glaredb", rev = "f71c2f0ad220ac54c84724330224f43c860bffb9" }
pgrepr = { git = "https://github.com/GlareDB/glaredb", rev = "f71c2f0ad220ac54c84724330224f43c860bffb9" }
datafusion_ext = { git = "https://github.com/GlareDB/glaredb", rev = "f71c2f0ad220ac54c84724330224f43c860bffb9" }
arrow_util = { git = "https://github.com/GlareDB/glaredb", rev = "f71c2f0ad220ac54c84724330224f43c860bffb9" }
terminal_util = { git = "https://github.com/GlareDB/glaredb", rev = "f71c2f0ad220ac54c84724330224f43c860bffb9" }
