[package]
name = "r-glaredb"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
savvy = "0.6.4"
datafusion = { version = "36.0.0", features = ["avro"] }
tokio = { version = "1", features = ["full"] }
arrow = { version = "50.0.0", features = ["ffi"] }
thiserror = "1.0"
url = "2.5.0"
anyhow = "1.0.83"
async-trait = "0.1.80"
futures = "0.3.30"
uuid = "1.8.0"
once_cell = "1.19.0"
glaredb = { git = "https://github.com/GlareDB/glaredb", rev = "c7befa9b1624ad08cdea0513ca0ae3483a3e1d9f" }
sqlexec = { git = "https://github.com/GlareDB/glaredb", rev = "c7befa9b1624ad08cdea0513ca0ae3483a3e1d9f" }
metastore = { git = "https://github.com/GlareDB/glaredb", rev = "c7befa9b1624ad08cdea0513ca0ae3483a3e1d9f" }
arrow_util = { git = "https://github.com/GlareDB/glaredb", rev = "c7befa9b1624ad08cdea0513ca0ae3483a3e1d9f" }
terminal_util = { git = "https://github.com/GlareDB/glaredb", rev = "c7befa9b1624ad08cdea0513ca0ae3483a3e1d9f" }

# Prevent dynamic linking of lzma, which comes from datafusion
lzma-sys = { version = "*", features = ["static"] }
