# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib glaredb, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}


sql <- function(query, connection = NULL) {
  connection <- .savvy_extract_ptr(connection, "RGlareDbConnection")
  .savvy_wrap_RGlareDbExecutionOutput(.Call(savvy_sql__impl, query, connection))
}


prql <- function(query, connection = NULL) {
  connection <- .savvy_extract_ptr(connection, "RGlareDbConnection")
  .savvy_wrap_RGlareDbExecutionOutput(.Call(savvy_prql__impl, query, connection))
}


execute <- function(query, connection = NULL) {
  connection <- .savvy_extract_ptr(connection, "RGlareDbConnection")
  .savvy_wrap_RGlareDbExecutionOutput(.Call(savvy_execute__impl, query, connection))
}


connect <- function(cloud_addr, disable_tls, data_dir_or_cloud_url = NULL, spill_path = NULL, location = NULL, storage_options = NULL, env = NULL) {
  .savvy_wrap_RGlareDbConnection(.Call(savvy_connect__impl, cloud_addr, disable_tls, data_dir_or_cloud_url, spill_path, location, storage_options, env))
}

### wrapper functions for RGlareDbConnection

RGlareDbConnection_sql <- function(self) {
  function(query) {
    .savvy_wrap_RGlareDbExecutionOutput(.Call(savvy_RGlareDbConnection_sql__impl, self, query))
  }
}

RGlareDbConnection_prql <- function(self) {
  function(query) {
    .savvy_wrap_RGlareDbExecutionOutput(.Call(savvy_RGlareDbConnection_prql__impl, self, query))
  }
}

RGlareDbConnection_execute <- function(self) {
  function(query) {
    .savvy_wrap_RGlareDbExecutionOutput(.Call(savvy_RGlareDbConnection_execute__impl, self, query))
  }
}

.savvy_wrap_RGlareDbConnection <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
    e$sql <- RGlareDbConnection_sql(ptr)
  e$prql <- RGlareDbConnection_prql(ptr)
  e$execute <- RGlareDbConnection_execute(ptr)
  
  class(e) <- "RGlareDbConnection"
  e
}



RGlareDbConnection <- new.env(parent = emptyenv())

### associated functions for RGlareDbConnection

RGlareDbConnection$default_in_memory <- function() {
  .savvy_wrap_RGlareDbConnection(.Call(savvy_RGlareDbConnection_default_in_memory__impl))
}


### wrapper functions for RGlareDbExecutionOutput

RGlareDbExecutionOutput_print <- function(self) {
  function() {
  invisible(.Call(savvy_RGlareDbExecutionOutput_print__impl, self))
  }
}

RGlareDbExecutionOutput_to_table <- function(self) {
  function() {
    .savvy_wrap_RGlareDbTable(.Call(savvy_RGlareDbExecutionOutput_to_table__impl, self))
  }
}

.savvy_wrap_RGlareDbExecutionOutput <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
    e$print <- RGlareDbExecutionOutput_print(ptr)
  e$to_table <- RGlareDbExecutionOutput_to_table(ptr)
  
  class(e) <- "RGlareDbExecutionOutput"
  e
}



RGlareDbExecutionOutput <- new.env(parent = emptyenv())

### associated functions for RGlareDbExecutionOutput



### wrapper functions for RGlareDbTable

RGlareDbTable_print <- function(self) {
  function() {
  invisible(.Call(savvy_RGlareDbTable_print__impl, self))
  }
}

RGlareDbTable_export_stream <- function(self) {
  function(stream_ptr) {
  invisible(.Call(savvy_RGlareDbTable_export_stream__impl, self, stream_ptr))
  }
}

.savvy_wrap_RGlareDbTable <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
    e$print <- RGlareDbTable_print(ptr)
  e$export_stream <- RGlareDbTable_export_stream(ptr)
  
  class(e) <- "RGlareDbTable"
  e
}



RGlareDbTable <- new.env(parent = emptyenv())

### associated functions for RGlareDbTable

RGlareDbTable$import_stream <- function(stream_ptr) {
  .savvy_wrap_RGlareDbTable(.Call(savvy_RGlareDbTable_import_stream__impl, stream_ptr))
}


### wrapper functions for RGlareDbTokioRuntime


.savvy_wrap_RGlareDbTokioRuntime <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  
  
  class(e) <- "RGlareDbTokioRuntime"
  e
}



RGlareDbTokioRuntime <- new.env(parent = emptyenv())

### associated functions for RGlareDbTokioRuntime



