# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib glaredb, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_glaredb__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_glaredb__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}


`connect` <- function(`cloud_addr`, `disable_tls`, `env`, `data_dir_or_cloud_url` = NULL, `spill_path` = NULL, `location` = NULL, `storage_options` = NULL) {
  .savvy_wrap_RGlareDbConnection(.Call(savvy_connect__impl, `cloud_addr`, `disable_tls`, `env`, `data_dir_or_cloud_url`, `spill_path`, `location`, `storage_options`))
}


`execute` <- function(`query`, `connection` = NULL) {
  `connection` <- .savvy_extract_ptr(`connection`, "RGlareDbConnection")
  .savvy_wrap_RGlareDbExecutionOutput(.Call(savvy_execute__impl, `query`, `connection`))
}

#' @rdname glaredb_execute
#' @export
#' @order 3
`glaredb_prql` <- function(`query`, `connection` = NULL) {
  `connection` <- .savvy_extract_ptr(`connection`, "RGlareDbConnection")
  .savvy_wrap_RGlareDbExecutionOutput(.Call(savvy_glaredb_prql__impl, `query`, `connection`))
}

#' @rdname glaredb_execute
#' @export
#' @order 2
`glaredb_sql` <- function(`query`, `connection` = NULL) {
  `connection` <- .savvy_extract_ptr(`connection`, "RGlareDbConnection")
  .savvy_wrap_RGlareDbExecutionOutput(.Call(savvy_glaredb_sql__impl, `query`, `connection`))
}

### wrapper functions for RGlareDbConnection


`.savvy_wrap_RGlareDbConnection` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- c("RGlareDbConnection", "savvy_glaredb__sealed")
  e
}



`RGlareDbConnection` <- new.env(parent = emptyenv())

### associated functions for RGlareDbConnection



class(`RGlareDbConnection`) <- c("RGlareDbConnection__bundle", "savvy_glaredb__sealed")

#' @export
`print.RGlareDbConnection__bundle` <- function(x, ...) {
  cat('RGlareDbConnection\n')
}

### wrapper functions for RGlareDbExecutionOutput

`RGlareDbExecutionOutput_print` <- function(self) {
  function() {
    invisible(.Call(savvy_RGlareDbExecutionOutput_print__impl, `self`))
  }
}

`RGlareDbExecutionOutput_to_table` <- function(self) {
  function() {
    .savvy_wrap_RGlareDbTable(.Call(savvy_RGlareDbExecutionOutput_to_table__impl, `self`))
  }
}

`.savvy_wrap_RGlareDbExecutionOutput` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`print` <- `RGlareDbExecutionOutput_print`(ptr)
  e$`to_table` <- `RGlareDbExecutionOutput_to_table`(ptr)

  class(e) <- c("RGlareDbExecutionOutput", "savvy_glaredb__sealed")
  e
}



`RGlareDbExecutionOutput` <- new.env(parent = emptyenv())

### associated functions for RGlareDbExecutionOutput



class(`RGlareDbExecutionOutput`) <- c("RGlareDbExecutionOutput__bundle", "savvy_glaredb__sealed")

#' @export
`print.RGlareDbExecutionOutput__bundle` <- function(x, ...) {
  cat('RGlareDbExecutionOutput\n')
}

### wrapper functions for RGlareDbTable

`RGlareDbTable_export_stream` <- function(self) {
  function(`stream_ptr`) {
    invisible(.Call(savvy_RGlareDbTable_export_stream__impl, `self`, `stream_ptr`))
  }
}

`RGlareDbTable_print` <- function(self) {
  function() {
    invisible(.Call(savvy_RGlareDbTable_print__impl, `self`))
  }
}

`.savvy_wrap_RGlareDbTable` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`export_stream` <- `RGlareDbTable_export_stream`(ptr)
  e$`print` <- `RGlareDbTable_print`(ptr)

  class(e) <- c("RGlareDbTable", "savvy_glaredb__sealed")
  e
}



`RGlareDbTable` <- new.env(parent = emptyenv())

### associated functions for RGlareDbTable

`RGlareDbTable`$`import_stream` <- function(`stream_ptr`) {
  .savvy_wrap_RGlareDbTable(.Call(savvy_RGlareDbTable_import_stream__impl, `stream_ptr`))
}


class(`RGlareDbTable`) <- c("RGlareDbTable__bundle", "savvy_glaredb__sealed")

#' @export
`print.RGlareDbTable__bundle` <- function(x, ...) {
  cat('RGlareDbTable\n')
}

