# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: pkgdown
on:
  push:
    branches:
      - main
    paths:
      - R/**
      - src/**
      - vignetts/**
      - _pkgdown.yml
      - DESCRIPTION
      - README.md
    tags:
      - v*
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/pkgdown.yml
      - R/**
      - src/**
      - vignetts/**
      - _pkgdown.yml
      - DESCRIPTION
      - README.md
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: more space
        uses: jlumbroso/free-disk-space@v1.3.1
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          Ncpus: "2"
          extra-repositories: https://community.r-multiverse.org # For the polars package

      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set rust target
        id: rust-target
        run: |
          echo "TARGET=$(rustc -vV | grep host | cut -d' ' -f2)" >>"$GITHUB_OUTPUT"

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "src/rust -> target"
          shared-key: ${{ steps.rust-target.outputs.TARGET }}

      - name: Build lib
        env:
          NOT_CRAN: "true"
        run: |
          if [[ ! -f "tools/lib-sums.tsv" ]]; then
            # make sure savvy is built from source because rust-cache doesn't work well.
            (find ~/.cargo/registry/ src/rust/target -name 'savvy-*' | xargs rm -rf) || true

            Rscript -e 'install.packages(c("pkgbuild", "nanoarrow"))'
            Rscript -e 'pkgbuild::compile_dll()'
            echo "LIBR_GLAREDB_PATH=$(pwd)/src/rust/target/${{ steps.rust-target.outputs.TARGET }}/debug/libr_glaredb.a" >>$GITHUB_ENV
          fi

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "src/rust -> target"
          shared-key: x86_64-unknown-linux-gnu
          save-if: "false"

      - uses: r-lib/actions/setup-r-dependencies@v2
        env:
          LIBR_GLAREDB_BUILD: "false"
        with:
          extra-packages: any::pkgdown
          needs: website

      - name: Build site
        run: |
          R CMD INSTALL --no-multiarch --with-keep.source .
          Rscript -e 'pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)'

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          clean: false
          branch: gh-pages
          folder: docs
